@startuml

class Juego
class Jugador
class Vibora
class Arena
class Comida
class Colisionable
class Dimension


Vibora o-- Arena
Jugador o-- Vibora

Vibora *-- Dimension
Arena *-- Colisionable
Arena *-- Comida

Vibora --|> Colisionable
Arena --|> Colisionable
Muro --|> Colisionable






@enduml